// <auto-generated />
using DbLocalizationProvider.AspNetCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DbLocalizationProvider.AspNetCore.Migrations
{
    [DbContext(typeof(LanguageEntities))]
    partial class LanguageEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbLocalizationProvider.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .HasMaxLength(100);

                    b.Property<bool>("FromCode");

                    b.Property<bool?>("IsHidden");

                    b.Property<bool?>("IsModified");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(1700);

                    b.HasKey("Id");

                    b.HasIndex("ResourceKey")
                        .IsUnique()
                        .HasName("IX_ResourceKey");

                    b.ToTable("LocalizationResources");
                });

            modelBuilder.Entity("DbLocalizationProvider.LocalizationResourceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Language")
                        .HasMaxLength(10);

                    b.Property<int>("ResourceId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("LocalizationResourceTranslations");
                });

            modelBuilder.Entity("DbLocalizationProvider.LocalizationResourceTranslation", b =>
                {
                    b.HasOne("DbLocalizationProvider.LocalizationResource", "LocalizationResource")
                        .WithMany("Translations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
